language: rust
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
      - qemu-user

# run builds for all the trains
rust:
  - nightly
  - beta
  - 1.8.0
  - 1.7.0
  - 1.6.0

before_script:
  - sh prepare-script.sh

# the main build
script:
  - cargo build --target arm-unknown-linux-gnueabihf
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug"
  - cargo build --target arm-unknown-linux-gnueabihf --no-default-features --features="debug"
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug real-sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="real-sim"
  # Still testing left, maybe we should run a simple script
