language: rust
sudo: required
dist: trusty
rust:
  - 1.5.0
  - 1.6.0
  - beta
  - nightly
install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-linux-gnueabihf qemu-user
before_script:
    - sh prepare-script.sh
script:
  - cargo build --target arm-unknown-linux-gnueabihf
  - qemu-arm -L /usr/arm-linux-gnueabihf target/arm-unknown-linux-gnueabihf/debug/openstratos-*
