language: rust
sudo: required
dist: trusty
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - 1.4.0
  - 1.5.0
  - stable
  - beta
  - nightly
install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-linux-gnueabihf qemu-user
before_script:
    - sh prepare-script.sh
script:
  - cargo build --target $TARGET
  - qemu-arm -L /usr/arm-linux-gnueabihf target/$TARGET/debug/openstratos-test
