language: generic
os:
  - linux
dist: trusty
sudo: false

# Build for all chains since Rust 1.8.0 (not available for prior versions)
env:
  - RUST=nightly
  - RUST=beta
  - RUST=stable
  - RUST=1.9.0
  - RUST=1.8.0

# Install rust
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup toolchain install $RUST
  - rustup default $RUST
  - rustup target add arm-unknown-linux-gnueabihf
  - rustc -V
  - cargo -V
  - cp scripts/config ~/.cargo/config
  - git clone https://github.com/raspberrypi/tools.git ~/pi-tools
  - cp scripts/gcc-sysroot ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - chmod +x ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot

# the main build
script:
  - ./cross64 "build -v"
  - ./cross64 "build -v --features=\"debug\""
  - ./cross64 "build -v --no-default-features --features=\"debug\""
  - ./cross64 "build -v --features=\"debug sim\""
  - ./cross64 "build -v --features=\"debug real-sim\""
  - ./cross64 "build -v --features=\"sim\""
  - ./cross64 "build -v --features=\"real-sim\""
  # Still testing left, maybe we should run a simple script
