language: generic
os:
  - linux
dist: trusty
sudo: false

# Build for all chains since Rust 1.8.0 (not available for prior versions)
env:
  - RUST=nightly
  - RUST=beta
  - RUST=stable
  - RUST=1.9.0
  - RUST=1.8.0

# Install rust
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup toolchain install $RUST
  - rustup default $RUST
  - rustup target add arm-unknown-linux-gnueabihf
  - rustc -V
  - cargo -V
  - cp scripts/config ~/.cargo/config
  - git clone https://github.com/raspberrypi/tools.git ~/pi-tools
  - cp scripts/gcc-sysroot ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - chmod +x ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot
  - export SYSROOT="~/pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot"
  - export PATH="~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin":$PATH
  - export CC="~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot"
  - export AR="~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar"

# the main build
script:
  - cargo build --target arm-unknown-linux-gnueabihf
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug"
  - cargo build --target arm-unknown-linux-gnueabihf --no-default-features --features="debug"
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="debug real-sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="sim"
  - cargo build --target arm-unknown-linux-gnueabihf --features="real-sim"
  # Still testing left, maybe we should run a simple script
