[package]
name = "openstratos"
version = "2.0.0-dev"
authors = ["Razican <razican@protonmail.ch>"]

[features]
default = ["power-off"]
power-off = []
debug = []
sim = []
real-sim = []

[dependencies]
time = "0.1"
log = "0.3"
fern = "0.3"
